# Generated by Django 5.1.7 on 2025-04-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BingoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestname', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('lobby_id', models.CharField(max_length=100)),
            ],
        ),
    ]
